name: sales_counter
description: Loyalty "Sales counter"
publish_to: 'none'
version: 0.0.0+6
environment:
  sdk: '>=2.19.1 <3.7.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  #state manager
  flutter_riverpod: ^2.2.0
  # data
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # localizations
  intl_utils: ^2.8.1
  # router
  go_router: ^6.0.7
  # QR code generator
  pretty_qr_code: ^2.0.3
  # uuid generator
  uuid: ^3.0.7
  # svg
  #flutter_svg: ^1.1.6
  #Utils
  #collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
  arb_dir: lib/core/localized/l10n
  output_dir: lib/core/localized/generated
  main_locale: en
flutter_assets_generator:
  output_dir: core\resources
  output_filename: app_assets
  class_name: AppAssets
